/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Day5RouteImport } from './routes/day5'
import { Route as Day4RouteImport } from './routes/day4'
import { Route as Day3RouteImport } from './routes/day3'
import { Route as Day2RouteImport } from './routes/day2'
import { Route as Day1RouteImport } from './routes/day1'
import { Route as IndexRouteImport } from './routes/index'

const Day5Route = Day5RouteImport.update({
  id: '/day5',
  path: '/day5',
  getParentRoute: () => rootRouteImport,
} as any)
const Day4Route = Day4RouteImport.update({
  id: '/day4',
  path: '/day4',
  getParentRoute: () => rootRouteImport,
} as any)
const Day3Route = Day3RouteImport.update({
  id: '/day3',
  path: '/day3',
  getParentRoute: () => rootRouteImport,
} as any)
const Day2Route = Day2RouteImport.update({
  id: '/day2',
  path: '/day2',
  getParentRoute: () => rootRouteImport,
} as any)
const Day1Route = Day1RouteImport.update({
  id: '/day1',
  path: '/day1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day1': typeof Day1Route
  '/day2': typeof Day2Route
  '/day3': typeof Day3Route
  '/day4': typeof Day4Route
  '/day5': typeof Day5Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day1': typeof Day1Route
  '/day2': typeof Day2Route
  '/day3': typeof Day3Route
  '/day4': typeof Day4Route
  '/day5': typeof Day5Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/day1': typeof Day1Route
  '/day2': typeof Day2Route
  '/day3': typeof Day3Route
  '/day4': typeof Day4Route
  '/day5': typeof Day5Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day1' | '/day2' | '/day3' | '/day4' | '/day5'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/day1' | '/day2' | '/day3' | '/day4' | '/day5'
  id: '__root__' | '/' | '/day1' | '/day2' | '/day3' | '/day4' | '/day5'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Day1Route: typeof Day1Route
  Day2Route: typeof Day2Route
  Day3Route: typeof Day3Route
  Day4Route: typeof Day4Route
  Day5Route: typeof Day5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/day5': {
      id: '/day5'
      path: '/day5'
      fullPath: '/day5'
      preLoaderRoute: typeof Day5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day4': {
      id: '/day4'
      path: '/day4'
      fullPath: '/day4'
      preLoaderRoute: typeof Day4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day3': {
      id: '/day3'
      path: '/day3'
      fullPath: '/day3'
      preLoaderRoute: typeof Day3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day2': {
      id: '/day2'
      path: '/day2'
      fullPath: '/day2'
      preLoaderRoute: typeof Day2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day1': {
      id: '/day1'
      path: '/day1'
      fullPath: '/day1'
      preLoaderRoute: typeof Day1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Day1Route: Day1Route,
  Day2Route: Day2Route,
  Day3Route: Day3Route,
  Day4Route: Day4Route,
  Day5Route: Day5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
